const {test, expect} = require('@playwright/test');
const urls = require('../../config/urls.json');
const { BasePage } = require('../../pages/basePage');
test('verify Renewable Energy Quiz Functionality', async ({ page }) => {
  test.setTimeout(120000);
    const base = new BasePage(page);
    await base.open(urls.base);
    await base.acceptCookies();
    await page.waitForLoadState('load');
    await page.waitForTimeout(1000);
    const searchIcon = page.locator("//button[@class='search']");
    await expect(searchIcon).toBeVisible({ timeout: 1000 });
    await searchIcon.isEnabled({ timeout: 1000 });
    await searchIcon.click();
    await base.handleLocationVirginia();
    await page.waitForTimeout(1000);
    await searchIcon.click();
    const searchInput=page.locator('#search-box-input');
    await expect(searchInput).toBeVisible({ timeout: 100 });
    await searchInput.fill('Renewable Energy Quiz');
    await page.waitForTimeout(100);
    await page.keyboard.press('Enter');
    await page.waitForLoadState('load');
    await page.waitForTimeout(500);
    //await page.waitForSelector("//*[@id='coveo01cd4840']//*[@class='coveo-result-list-container coveo-list-layout-container']//*[@class='coveo-list-layout CoveoResult']");
    await base.CoveoresultIsVisible();
    const result = page.locator("//a[contains(@class,'CoveoResultLink')]//h4[normalize-space()='Renewable Energy Quiz']");
    await page.waitForTimeout(3000);
    await expect(result).toBeVisible();
    await result.click();
    await page.waitForLoadState('load');
    await page.waitForTimeout(100);
    const currentUrl = page.url();
    if (currentUrl.includes('/virginia/renewable-energy-programs/renewable-energy-101/quiz')) {
     console.log("Renewable energy quiz page loaded successfully:", currentUrl);
    }   else {console.log("Failed to load the correct page.");}
    const quizSection= page.locator('.quiz-box');
    await quizSection.scrollIntoViewIfNeeded();
    const q1= page.locator("//*[@id='energy_quiz']//*[@class='question-cta d-block']//*[@class='answer-list']/label[1]/span[1]/i");
    await q1.click();
    await page.waitForTimeout(500);
    const nextbtn= page.locator("//*[@class='question-cta d-block']//*[@class='quiz-btn']");
    const backbtn= page.locator("//*[@class='question-cta d-block']//*[@class ='quiz-btn-back']");
    await nextbtn.click();
    await page.waitForTimeout(500);
    await backbtn.isVisible();
    await backbtn.click();
    await page.waitForTimeout(500);
    const q1selected= page.locator("//i[contains(@class,'fa-check-circle')]/ancestor::label//span[@class='answer-label']");
    const q1text= await q1selected.innerText();
    console.log("Question 1 selected answer:", q1text);
    await nextbtn.click();
    await page.waitForTimeout(500);
    const q2= page.locator("//*[@id='energy_quiz']//*[@class='question-cta d-block']//*[@class='answer-list']/label[2]/span[1]/i");
    await q2.click();
    const q2selected= page.locator("(//i[contains(@class,'fa-check-circle')]/ancestor::label//span[@class='answer-label'])[2]");;
    const q2text= await q2selected.innerText();
    console.log("Question 2 selected answer:", q2text);
    await page.waitForTimeout(500);
    await nextbtn.click();
    await page.waitForTimeout(500);
    const q3= page.locator("//*[@id='energy_quiz']//*[@class='question-cta d-block']//*[@class='answer-list']/label[1]/span[1]/i");
    await q3.click();
    const q3selected= page.locator("(//i[contains(@class,'fa-check-circle')]/ancestor::label//span[@class='answer-label'])[3]");
    const q3text= await q3selected.innerText();
    console.log("Question 3 selected answer:", q3text);
    await page.waitForTimeout(500);
    await nextbtn.click();
    await page.waitForTimeout(500);
    const q4= page.locator("//*[@id='energy_quiz']//*[@class='question-cta d-block']//*[@class='answer-list']/label[1]/span[1]/i");
    await q4.click();
    const q4selected= page.locator("(//i[contains(@class,'fa-check-circle')]/ancestor::label//span[@class='answer-label'])[4]");
    const q4text= await q4selected.innerText();
    console.log("Question 4 selected answer:", q4text);
    await page.waitForTimeout(500);
    await nextbtn.click();
    const quizResult= page.locator("//*[@class='rich-text-quiz-result']");
    //const resultText= await quizResult.innerText();
    await expect(quizResult).toBeVisible();
    //console.log("Quiz Result Text:", resultText);


});